config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root 'events#index'
  
  resources :users

  resources :events

  resources :attendances

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
	belongs_to :user
	belongs_to :event

	after_create :attendance_send

	def attendance_send
    UserMailer.attendance_email(self).deliver_now
  	end

end

app/models/event.rb
class Event < ApplicationRecord
	belongs_to :user

	has_many :attendances
	has_many :users, through: :attendances

	validates :start_date, presence: true #validate :start_in_future
	validates :duration, presence: true #validate :multiple_of_5
	validates :title, presence: true, length: { :within => 5..140}
	validates :description, presence: true, length: { :within => 20..1000}
	validates :price, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 1000}
	validates :location, presence: true

	def start_in_future
		if start_date != nil && Time.now > start_date
		then puts "La date choisie doit être dans le futur ! "
		end
	end

	def multiple_of_5
		if duration != nil && duration % 5 != 0
		then puts "La durée doit être un multiple de 5"
		end
	end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

	has_many :attendances
	has_many :events, through: :attendances

	after_create :welcome_send
	
	def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	before_action :configure_devise_parameters, if: :devise_controller?

def configure_devise_parameters
  devise_parameter_sanitizer.permit(:sign_up) {|u| u.permit(:first_name, :last_name, :is_alive, :email, :password, :password_confirmation)}
  devise_parameter_sanitizer.permit(:account_update) {|u| u.permit(:first_name, :last_name, :is_alive, :email, :password, :password_confirmation)}
end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	
before_action :authenticate_user!, only: [:new, :create]

	def index
		@event = Event.all
	end

	def show
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	
	def index
		@users = User.all
	end

	def new
		@user = User.new
	end

	def show
		@user = User.find(current_user.id)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/index.html.erb
<div class="jumbotron">

  <% if current_user %>
  <h1 class="display-4"> Bienvenue <%= current_user.first_name %> ! </h1>
  <% else %>
  <h1 class="display-4"> Bienvenue ! </h1>
  <% end %>

  <p class="lead"> Voici notre site de planifications d'évènements </p>
  <hr class="my-4">
  <p class="lead">
    <a class="btn btn-primary btn-lg" href="events/new" role="button"> Créer un évènement </a>
  </p>
  

</div>

<h2> Voici la liste des prochains évènements : </h2>

<% @event.each do |event| %>

  <%= event.title %> <br>
  <%= event.description %> <br>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eventbrite</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

     <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

  </head>

  <body>

    <!-- NAVBAR -->

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark" style="background-color: #e3f2fd;">
    <div class="container-fluid">
    <a class="navbar-brand" href="#"></a>
    <%= link_to 'Event Project', events_path, :class => 'navbar-brand' %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    
  <ul class="navbar-nav mr-auto">
  <li class="nav-item active">
  <%= link_to 'Créer un évènement', new_event_path, :class => 'nav-link' %>
  </li>
  </ul>

    <ul class="navbar-nav ml-auto">

          <!-- si utilisateur connecté -->

          <% if current_user %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle active" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <%= current_user.first_name %>
              </a>
              <div class="dropdown-menu bg-dark" aria-labelledby="navbarDropdown">
                <%= link_to 'Mon profil', user_path(current_user.id), :class => "dropdown-item text-light" %>
                <%= link_to 'Déconnexion', destroy_user_session_path,method: :delete, :class => "dropdown-item text-light" %>
              </div>
            </li>

          <!-- si non connecté -->

          <% else%>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle active" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Connexion / Inscription
              </a>
              <div class="dropdown-menu bg-dark" aria-labelledby="navbarDropdown">
                <%= link_to 'Connexion', new_user_session_path, :class => "dropdown-item text-light" %>
                <%= link_to 'Inscription', new_user_registration_path, :class => "dropdown-item text-light" %>
              </div>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>


    <%= yield %>


    <!-- javascript pour le dropdown button -->

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

  </body>
</html>

app/views/users/new.html.erb
<!DOCTYPE html>
<html>

<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <br><br><br>
      <%= form_for resource, as: resource_name, url: registration_path(resource_name), html: { class: "form-signin mt-3" } do |f| %>
        <h1 class="h3 mb-3 font-weight-normal text-center">Sign up</h1>
        <%= devise_error_messages! %>
        <div class="form-group">
          <%= f.label :email, "Email" %><br />
          <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :password %>
          <% if @minimum_password_length %>
          <em>(<%= @minimum_password_length %> characters minimum)</em>
          <% end %><br />
          <%= f.password_field :password, autocomplete: "new-password", class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :password_confirmation %><br />
          <%= f.password_field :password_confirmation, autocomplete: "new-password", class: "form-control" %>
        </div>
        <div class="actions mt-5">
          <%= f.submit "Sign up", class: "btn btn-lg btn-primary btn-block" %>
        </div>
      <% end %>
      <%= render "devise/shared/links" %>
    </div>
  </div>
</div>

</html>

app/views/users/show.html.erb
<!DOCTYPE html>
<html>

<h1>Mon profil</h1>

<p>
  <strong>Prénom:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Nom:</strong>
  <%= @user.last_name %>
</p>


</html>